services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./database.db:/code/database.db
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
